### ISSUE TITLE
How integrate this patch in a SDK 3/4 Alfresco project

### ISSUE THREAD

**Issue by p4535992** [keensoft/alf-21970-repo#2]
Hi this project worked perfectly, i wonder ,  can i integrate this java class in my "AMP/JAR" SDK 3/4 of Alfresco?
There is a specific directory for the maven project or i just need to put under "src/main/java" ?

**Comment by angelborroy** [comment]
This patch is part of Alfresco core libraries, so it cannot be used in a module project (AMP/JAR). Nevertheless, this patch is applied to Alfresco 6.x, so it will become available by default when you upgrade your installation.
